image: luishmcmoreno/angular-cli-docker:master
pipelines:
  default:
      - step:
          script:
            - npm install -g rxjs
            - npm install --quiet
            - ng build
            - apt-get update
            - apt-get -qq install sshpass -y --force-yes
            - cd dist
            - sshpass -p $FTP_PASSWORD scp -o StrictHostKeyChecking=no -r * $FTP_USERNAME@198.199.65.29:/home/pluritest/painel.hackathonbdmg.pluritest.com.br